### ISSUE TITLE
Some writing guidelines we should establish to help everyone reading

### ISSUE THREAD

**Issue by Zircoz** [bitsacm/Slack-Stock-DAG#25]
There should be a general editorial styling pattern which every contribution would follow. Here are a few recommendations.
- Using hyperlinking wherever possible
- Using common abbreviations and making a list of them somewhere, anyone who adds something should add the new common abbreviations (if any) they have used to the common list.

**Comment by Zircoz** [comment]
Also, why don't we refer people to MIT OCW course pages directly instead of their Youtube playlists? In my opinion, MIT OCW course pages would be more helpful since they generally have lecture notes, handouts and more along with lectures.

**Comment by 7vik** [comment]
@Zircoz Thanks! I've added these guidelines in the README for ease.
